### ISSUE TITLE
Experiencing timeout error

### ISSUE THREAD

**Issue by jsavage** [perrinjerome/mitene_download#7]
I am seeing the following timeout after the script has been running for a few mins.
Only some of the available jpegs are being downloaded successfully as are *.md files.
Videos are being downloaded without their file extension although if I download manually through a browser they come with .mp4
I suspect that may be a separate issue from the Timeout. 

Can anyone advise a method for increasing or avoiding the timeout?

```
pi@raspberrypi:~/mitene/mitene_download $ python mitene_download.py https://mitene.us/f/xxxxx
Traceback (most recent call last):
  File "/home/pi/mitene/mitene_download/mitene_download.py", line 147, in <module>
    main()
  File "/home/pi/mitene/mitene_download/mitene_download.py", line 143, in main
    loop.run_until_complete(async_main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/mitene/mitene_download/mitene_download.py", line 137, in async_main
    await gather_with_concurrency(4, *download_coroutines)
  File "/home/pi/mitene/mitene_download/mitene_download.py", line 26, in gather_with_concurrency
    await asyncio.gather(*(sem_task(task) for task in tasks))
  File "/home/pi/mitene/mitene_download/mitene_download.py", line 24, in sem_task
    await task
  File "/home/pi/mitene/mitene_download/mitene_download.py", line 43, in download_media
    async for chunk in r.content.iter_chunked(1024):
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 35, in __anext__
    rv = await self.read_func()
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 385, in read
    await self._wait("read")
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

```

**Comment by perrinjerome** [comment]
Ah yes, there is a problem with videos without extension ( #4 ). I plan to take a look when I have  time.

I did not notice timeout problems, but I see that the library used for HTTP has a timeout of 5 minutes ( 
https://docs.aiohttp.org/en/stable/client_quickstart.html#aiohttp-client-timeouts ). I guess we can try to increase this, do you want to try #9 ?

**Comment by jsavage** [comment]
Hi Jerome,  many thanks for looking at this. yes, i think that is worth
trying.
James

**Comment by perrinjerome** [comment]
Thanks, actually I just published a new version on pypi with this fix. Let me know if that was not enough. Thanks a lot for all your comments
